import Footer from './components/Footer'
import FooterWrapper from './components/FooterWrapper'
import Header from './components/Header'
import PageWrapper from './components/PageWrapper'
import './globals.css'
import { Roboto } from "next/font/google"

const notoSans = Roboto({subsets: ['latin'], weight: "300" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//prata
//Oranienbaum
//raleway

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`dark:bg-[#161416] dark:text-white ${notoSans.className}`}>
        <PageWrapper>
          <Header />
          {children}        
          {/* <FooterWrapper>
            <Footer />
          </FooterWrapper> */}
          </PageWrapper>
        </body>
      {/* <body className={`dark:bg-[#0B1229]`}>{children}</body> */}
    </html>
  )
}
