import Footer from './components/Footer'
import FooterWrapper from './components/FooterWrapper'
import Header from './components/Header'
import PageWrapper from './components/PageWrapper'
import './globals.css'
import { Noto_Sans_Display } from "next/font/google"

const notoSans = Noto_Sans_Display({subsets: ['latin'], weight: "300" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//prata
//Oranienbaum
//raleway

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`dark:bg-[#0e0e0f] dark:text-white ${notoSans.className}`}>
        {/* <PageWrapper> */}
          <Header />
          {children}        
          {/* </PageWrapper> */}
          <FooterWrapper>
            <Footer />
          </FooterWrapper>
        </body>
      {/* <body className={`dark:bg-[#0B1229]`}>{children}</body> */}
    </html>
  )
}
