import Footer from './components/Footer'
import Header from './components/Header'
import './globals.css'
import { Noto_Sans_Display } from "next/font/google"

const notoSans = Noto_Sans_Display({subsets: ['latin'], weight: "300" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//prata
//Oranienbaum
//raleway

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`dark:bg-[#100916] dark:text-white ${notoSans.className}`}>
        <Header />
        {children}
        <Footer />
        </body>
      {/* <body className={`dark:bg-[#0B1229]`}>{children}</body> */}
    </html>
  )
}
